In [ ]:
classification:
it is one of the supervised learning algorithm used to work on categorical data

In [ ]:
logistic regression
knn
svm
naive bayes
decision tree
random forest

In [ ]:
logitic regression:
it is used for binary classification
it is also called as sigmoid function where the value lies between 0 and 1
it has the threshold value that

In [ ]:
knn:
it is used to classify the new data based on the majority of the voting with the help of euclidean distance formula

choose the k value(eg:3 or 5)
calculate the eucldiean distance formula
pick the k nearest values
take the majority of the voting
finally assign which class it belongs to

In [ ]:
svm(support vector machine)
it is one of the ml algorithm which is used to find the best boundary(hyperplane)
between the classes

w.x+b=0

In [ ]:
naive bayes:
it is a probabilistic classification based on the theorem(bayes)
p(a/b)=p(b/a).p(a)/p(b)

types of naive bayes:
1.gaussian(continuous data)
2.multinomial(for text data)
3.bernoulli(binary features)

In [ ]:
decision tree:
it uses tree like structure to make decisions 
it consists of node,branches and leaf
it follows asm(Attribute selection measure):
1.information gain
2.gini index

it faces the overfitting problem to reduce this we have random forest

In [ ]:
random forest:
it is also called as ensemble learning
it consists of bagging and boosting techniques
it have multiple decision trees

In [ ]:
life cycle of ml:
business problem
data collection
data preparation/preppocessing/wrangling
analyse the data
feature engineering
model selection
model training
model evaluation
deployement
maintaining and monitoring

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
iris business problem:
species---setosa,versicolor,virginica

sepal_length
sepal_width
petal_length
petal_width

In [ ]:
pip install scikit-learn

In [4]:
from sklearn.datasets import load_iris

In [5]:
data=load_iris()

In [6]:
print(data.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print(data.target_names)

['setosa' 'versicolor' 'virginica']


In [8]:
x=data.data

In [9]:
y=data.target

In [10]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [17]:
y_pred=model.predict(x_test)

In [18]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [19]:
from sklearn.metrics import accuracy_score,classification_report
acc=accuracy_score(y_test,y_pred)

In [20]:
acc

1.0

In [21]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        10\n           1       1.00      1.00      1.00         9\n           2       1.00      1.00      1.00        11\n\n    accuracy                           1.00        30\n   macro avg       1.00      1.00      1.00        30\nweighted avg       1.00      1.00      1.00        30\n'

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [24]:
y_pred=model.predict(x_test)

In [25]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [26]:
accuracy_score(y_test,y_pred)

1.0

In [27]:
from sklearn.svm import SVC

In [28]:
model=SVC()
model.fit(x_train,y_train)

SVC()

In [29]:
y_pred=model.predict(x_test)

In [30]:
accuracy_score(y_test,y_pred)

1.0

In [31]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [32]:
y_pred=model.predict(x_test)

In [33]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [34]:
accuracy_score(y_test,y_pred)

1.0

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [37]:
y_pred=model.predict(x_test)

In [38]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [40]:
accuracy_score(y_test,y_pred)

1.0

In [41]:
from sklearn.ensemble import AdaBoostClassifier

In [43]:
model=AdaBoostClassifier()
model.fit(x_train,y_train)

C:\Users\Kavyashree N\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier()

In [44]:
y_pred=model.predict(x_test)

In [45]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [46]:
accuracy_score(y_test,y_pred)

1.0

In [47]:
pip install xgboost

   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.8/101.7 MB 3.7 MB/s eta 0:00:28
    --------------------------------------- 2.4/101.7 MB 5.8 MB/s eta 0:00:18
   - -------------------------------------- 3.7/101.7 MB 5.7 MB/s eta 0:00:18
   - -------------------------------------- 4.2/101.7 MB 6.0 MB/s eta 0:00:17
   -- ------------------------------------- 6.0/101.7 MB 5.7 MB/s eta 0:00:17
   -- ------------------------------------- 7.1/101.7 MB 5.6 MB/s eta 0:00:17
   --- ------------------------------------ 8.9/101.7 MB 6.0 MB/s eta 0:00:16
   ---- ----------------------------------- 10.2/101.7 MB 6.4 MB/s eta 0:00:15
   ----- ---------------------------------- 12.8/101.7 MB 6.7 MB/s eta 0:00:14
   ----- ---------------------------------- 14.4/101.7 MB 6.8 MB/s eta 0:00:13
   ------ --------------------------------- 15.5/101.7 MB 6.9 MB/s eta 0:00:13
   ------ --------------------------------- 17.6/101.7 MB 7.0 MB/s 

In [48]:
from xgboost import XGBClassifier

In [49]:
model=XGBClassifier()
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [50]:
y_pred=model.predict(x_test)

In [51]:
accuracy_score(y_test,y_pred)

1.0

In [52]:
from sklearn.datasets import load_breast_cancer

In [53]:
df=load_breast_cancer()

In [54]:
df

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [55]:
df.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [56]:
df.target_names


array(['malignant', 'benign'], dtype='<U9')

In [57]:
x=df.data

In [58]:
y=df.target

In [59]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [60]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [65]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [66]:
y_pred=model.predict(x_test)

In [67]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [68]:
accuracy_score(y_test,y_pred)

0.9736842105263158

In [69]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
model=KNeighborsClassifier()
model.fit(x_train,y_train)

KNeighborsClassifier()

In [71]:
y_pred=model.predict(x_test)

In [72]:
accuracy_score(y_test,y_pred)

0.9473684210526315

In [73]:
from sklearn.svm import SVC

In [74]:
model=SVC()
model.fit(x_train,y_train)

SVC()

In [75]:
y_pred=model.predict(x_test)

In [76]:
accuracy_score(y_test,y_pred)

0.9824561403508771

In [77]:
from sklearn.naive_bayes import GaussianNB

In [78]:
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [79]:
y_pred=model.predict(x_test)

In [81]:
accuracy_score(y_test,y_pred)

0.9649122807017544

In [82]:
from sklearn.tree import DecisionTreeClassifier

In [83]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [84]:
y_pred=model.predict(x_test)

In [85]:
accuracy_score(y_test,y_pred)

0.9385964912280702

In [86]:
from sklearn.ensemble import RandomForestClassifier

In [87]:
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [88]:
y_pred=model.predict(x_test)

In [89]:
accuracy_score(y_test,y_pred)

0.9649122807017544

In [ ]:
Assignment:
take any two datasets from kaggle and perform all the classification algorithms