task 1:

analyse the sales data:

total sales per region

average sales per month

best performing region

In [ ]:
import numpy as np

# Rows = Months, Columns = Regions
# Regions: North, South, East

sales = np.array([
    [200, 150, 300],   # Month 1
    [250, 180, 320],   # Month 2
    [300, 200, 350],   # Month 3
    [280, 210, 400]    # Month 4
])

print("Sales Data:\n", sales)

Sales Data:
 [[200 150 300]
 [250 180 320]
 [300 200 350]
 [280 210 400]]


In [ ]:
total_region_sales = np.sum(sales, axis=0)
print("Total Sales Per Region:", total_region_sales)


Total Sales Per Region: [1030  740 1370]


In [ ]:
avg_month_sales = np.mean(sales, axis=1)
print("Average Sales Per Month:", avg_month_sales)


Average Sales Per Month: [216.66666667 250.         283.33333333 296.66666667]


In [ ]:
best_region_index = np.argmax(total_region_sales)

regions = ["North", "South", "East"]

print("Best Performing Region:", regions[best_region_index])


Best Performing Region: East


task 2:

student ranking system(sorting)

In [ ]:
import numpy as np

students = np.array([
    (101, "Ravi", 85),
    (102, "Anita", 92),
    (103, "Kiran", 78),
    (104, "Meena", 95),
    (105, "Arjun", 88)
], dtype=[('id', 'i4'), ('name', 'U10'), ('marks', 'i4')])

print("Student Data:\n", students)


Student Data:
 [(101, 'Ravi', 85) (102, 'Anita', 92) (103, 'Kiran', 78)
 (104, 'Meena', 95) (105, 'Arjun', 88)]


In [ ]:
sorted_students = np.sort(students, order='marks')[::-1]

print("Students Ranked by Marks:\n", sorted_students)


Students Ranked by Marks:
 [(104, 'Meena', 95) (102, 'Anita', 92) (105, 'Arjun', 88)
 (101, 'Ravi', 85) (103, 'Kiran', 78)]


In [ ]:
print("\nStudent Ranking List:")
rank = 1
for student in sorted_students:
    print("Rank", rank, ":", student['name'], "- Marks:", student['marks'])
    rank += 1



Student Ranking List:
Rank 1 : Meena - Marks: 95
Rank 2 : Anita - Marks: 92
Rank 3 : Arjun - Marks: 88
Rank 4 : Ravi - Marks: 85
Rank 5 : Kiran - Marks: 78


task3:

production quality check

In [ ]:
import numpy as np

# Columns: ProductID, Produced Units, Defective Units
production = np.array([
    [101, 500, 20],
    [102, 600, 30],
    [103, 550, 25],
    [104, 700, 50],
    [105, 650, 15]
])

print("Production Data:\n", production)


Production Data:
 [[101 500  20]
 [102 600  30]
 [103 550  25]
 [104 700  50]
 [105 650  15]]


In [ ]:
produced = production[:, 1]
defective = production[:, 2]


In [ ]:
defect_rate = (defective / produced) * 100
print("Defect Percentage:\n", defect_rate)


Defect Percentage:
 [4.         5.         4.54545455 7.14285714 2.30769231]


In [ ]:
avg_defect = np.mean(defect_rate)
print("Average Defect Rate:", avg_defect)


Average Defect Rate: 4.5992007992007995


In [ ]:
poor_quality = production[defect_rate > avg_defect]

print("Poor Quality Products:\n", poor_quality)


Poor Quality Products:
 [[102 600  30]
 [104 700  50]]


In [ ]:
best_index = np.argmin(defect_rate)

print("Best Quality Product:", production[best_index])


Best Quality Product: [105 650  15]


task 4:

broadcasting in pricing system

In [ ]:
import numpy as np

# Product prices in different regions
#columns=regions
prices = np.array([
    [100, 110, 120],   # Product 1
    [200, 210, 220],   # Product 2
    [300, 310, 320]    # Product 3
])

print("Original Prices:\n", prices)


Original Prices:
 [[100 110 120]
 [200 210 220]
 [300 310 320]]


Apply Discount Using Broadcasting

Suppose each region has a different discount

Region discounts:

North → 10
South → 15
East → 20

In [ ]:
discount = np.array([10, 15, 20])

new_prices = prices - discount

print("Prices After Discount:\n", new_prices)


Prices After Discount:
 [[ 90  95 100]
 [190 195 200]
 [290 295 300]]


In [ ]:
#Add Tax Using Broadcasting

taxed_prices = new_prices * 1.05

print("Final Prices After Tax:\n", taxed_prices)


Final Prices After Tax:
 [[ 94.5   99.75 105.  ]
 [199.5  204.75 210.  ]
 [304.5  309.75 315.  ]]


task 5:
 create one data with numpy:

 customer id, age, purchase_amount region

 1.find the total customers

 2.extract only purchase column with slicing technique

 3.find the average purchase amount

 4.find the maximum and minimum purchase

 5.find the customers above average purchase

In [ ]:
import numpy as np

# Creating dataset
# Columns: ID, Age, Purchase, Region
data = np.array([
    [101, 25, 500, 1],
    [102, 30, 700, 2],
    [103, 22, 300, 1],
    [104, 35, 900, 3],
    [105, 28, 650, 2],
    [106, 40, 1200, 3]
])

print("Customer Data:\n", data)


Customer Data:
 [[ 101   25  500    1]
 [ 102   30  700    2]
 [ 103   22  300    1]
 [ 104   35  900    3]
 [ 105   28  650    2]
 [ 106   40 1200    3]]


In [ ]:
total_customers = data.shape[0]
print("Total Customers:", total_customers)

Total Customers: 6


In [ ]:
purchase = data[:, 2]
print("Purchase Amount Column:", purchase)

Purchase Amount Column: [ 500  700  300  900  650 1200]


In [ ]:
avg_purchase = np.mean(purchase)
print("Average Purchase Amount:", avg_purchase)

Average Purchase Amount: 708.3333333333334


In [ ]:
max_purchase = np.max(purchase)
min_purchase = np.min(purchase)

print("Maximum Purchase:", max_purchase)
print("Minimum Purchase:", min_purchase)

Maximum Purchase: 1200
Minimum Purchase: 300


In [ ]:
above_avg_customers = data[purchase > avg_purchase]

print("Customers Above Average Purchase:\n", above_avg_customers)

Customers Above Average Purchase:
 [[ 104   35  900    3]
 [ 106   40 1200    3]]


task 6:

create one dataset:
employee id,
employee name,
age,
salary

find the total salary of all employees

find the minimum salary of the employees

find the maximum salary of the employees

find the average age of employees

find the total number of employees

find the correlation between age and salary


In [ ]:
import numpy as np

# Creating structured dataset
employees = np.array([
    (101, "Ravi", 25, 30000),
    (102, "Anita", 30, 45000),
    (103, "Kiran", 28, 40000),
    (104, "Meena", 35, 55000),
    (105, "Arjun", 32, 50000)
], dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4'), ('salary', 'i4')])

print(employees)


[(101, 'Ravi', 25, 30000) (102, 'Anita', 30, 45000)
 (103, 'Kiran', 28, 40000) (104, 'Meena', 35, 55000)
 (105, 'Arjun', 32, 50000)]


In [ ]:
total_salary = np.sum(employees['salary'])
print("Total Salary:", total_salary)


Total Salary: 220000


In [ ]:
min_salary = np.min(employees['salary'])
print("Minimum Salary:", min_salary)


Minimum Salary: 30000


In [ ]:
max_salary = np.max(employees['salary'])
print("Maximum Salary:", max_salary)


Maximum Salary: 55000


In [ ]:
avg_age = np.mean(employees['age'])
print("Average Age:", avg_age)


Average Age: 30.0


In [ ]:
total_employees = len(employees)
print("Total Employees:", total_employees)


Total Employees: 5


In [ ]:
correlation = np.corrcoef(employees['age'], employees['salary'])
print("Correlation Matrix:\n", correlation)

print("Correlation between Age & Salary:", correlation[0,1])


Correlation Matrix:
 [[1.         0.98981298]
 [0.98981298 1.        ]]
Correlation between Age & Salary: 0.9898129771475668


1. What are broadcasting rules in NumPy?

Broadcasting is a technique in NumPy that allows arithmetic operations between arrays of different shapes without manually reshaping them.

Broadcasting Rules:

- NumPy compares array shapes from right to left.

- Two dimensions are compatible when:

They are equal, OR

One of them is 1.

- If dimensions are not compatible, broadcasting fails.

Example:

A shape = (3, 4)

B shape = (1, 4)

Result: B is stretched to match A → operation possible.

2. Why is broadcasting important in Machine Learning?

Broadcasting is important because:

- It avoids writing loops, making computations faster.

- It reduces memory usage.

- It simplifies mathematical operations on datasets.

- It is heavily used in vectorized ML calculations like:

 Feature scaling

Matrix operations

Neural network computations

3. What is a random number?

A random number is a number generated without a predictable pattern.

In NumPy, random numbers are used to:

- Simulate data

- Initialize ML model weights

- Perform sampling and probability experiments

Example:

np.random.rand()


4. Difference between rand() and randint()

| Feature | rand()                           | randint()               |
| ------- | -------------------------------- | ----------------------- |
| Type    | Float values                     | Integer values          |
| Range   | 0 to 1                           | User-defined range      |
| Usage   | Generates decimal random numbers | Generates whole numbers |


Example:

In [4]:
import numpy as np
np.random.rand(3)       # [0.34, 0.78, 0.12]
np.random.randint(1,10,3)  # [3, 7, 2]

array([5, 9, 2])

5. Explain sorting in NumPy

Sorting arranges elements in ascending or descending order.

NumPy provides:
np.sort(array)

Types of sorting:

Ascending (default)

Axis-based sorting for multi-dimensional arrays

Example:


In [6]:
arr = np.array([5,2,9])
np.sort(arr)   # [2,5,9]


array([2, 5, 9])

6. How can we search elements in NumPy?

Searching means finding positions of elements that match a condition.

Functions:

where() – returns index positions

searchsorted() – finds insertion index

argmax() / argmin() – returns index of max/min value

Example:

np.where(arr == 10)


7. What is joining in NumPy? Explain types.

Joining means combining two or more arrays into one.

Types:

i. Concatenate:

- Joins arrays along an axis.

- np.concatenate((a,b))

ii. Stack

- Joins arrays along a new axis.

- np.stack((a,b))

iii. Horizontal Stack (hstack)

- Joins column-wise.

iv. Vertical Stack (vstack)

- Joins row-wise.

8. Explain shape and reshape in NumPy

Shape:
It shows the dimensions of an array.

Example:

arr.shape → (rows, columns)


Reshape:
Changes the structure of an array without changing data.

Example:

arr.reshape(2,3)


Important rule:
Total elements must remain the same.

9. Difference between copy and view

| Feature        | Copy               | View               |
| -------------- | ------------------ | ------------------ |
| Memory         | New memory created | Shares same memory |
| Changes affect | Only copied array  | Both arrays        |
| Method         | arr.copy()         | arr.view()         |


10. Difference between flatten() and ravel()

Both convert multi-dimensional arrays into 1D arrays.

| Feature      | flatten()                | ravel()                    |
| ------------ | ------------------------ | -------------------------- |
| Memory       | Creates new copy         | Returns view when possible |
| Speed        | Slower                   | Faster                     |
| Modification | Does NOT affect original | May affect original        |


11. Difference between copy and shallow copy

i. Copy (Deep Copy):

- Creates completely independent data.

- Changes do not affect original.

ii. Shallow Copy:

- Copies references only.

- Changes in nested objects affect original.

In NumPy:

- copy() → deep copy

- view() → shallow copy