1. Why is NumPy Faster Than Python Lists?



1. NumPy Uses C Under the Hood

Python lists store elements as objects

NumPy arrays store elements in continuous memory blocks

Operations are executed in compiled C code, not Python loops

2. Fixed Data Type

Python list:

a = [1, 2, 3, 4]


Each element is a Python object → more memory → slower.

NumPy array:

import numpy as np
a = np.array([1,2,3,4])


All elements are same type (int32/int64) → less memory → faster.

 3. Vectorization

Instead of:

for i in range(len(a)):
    a[i] = a[i] * 2


We do:

a = a * 2


This avoids Python loop overhead.

 4. Memory Efficiency

Lists store references

NumPy stores raw values

Better cache utilization

Result: NumPy is 10x–100x faster for numerical operations.

2) What is Broadcasting?

Broadcasting allows NumPy to perform operations on arrays of different shapes.

Example 1: Scalar Broadcasting

In [ ]:
import numpy as np
a = np.array([1,2,3])
a + 5

array([6, 7, 8])

Example 2: Different Shapes

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

a + b

array([[11, 22, 33],
       [14, 25, 36]])

3.Features of NumPy

Multi-dimensional arrays

Broadcasting

Vectorization

Fast mathematical operations

Linear algebra support

Random number generation

Statistical functions

Memory efficient

Integration with ML libraries

4. Advantages of NumPy

High performance

Less memory usage

Easy matrix operations

Supports scientific computing

Large ecosystem support

5. What is Vectorization?

Vectorization means performing operations on entire arrays instead of loops.

Example:

Without NumPy:

In [ ]:
result = []
for i in range(5):
    result.append(i*2)

With NumPy:

In [ ]:
a = np.arange(5)
a * 2

array([0, 2, 4, 6, 8])

Why Important?

Faster execution

Cleaner code

Used heavily in ML

6. How NumPy Integrates with Machine Learning?

NumPy is the backbone of ML.

i. Data Storage

Datasets stored as arrays

Feature matrices → 2D arrays

ii. Linear Algebra

Matrix multiplication

Dot product

Inverse

Transpose

Example:

np.dot(X, W)

iii. Used By:

Scikit-learn

TensorFlow (internally)

PyTorch (conceptually similar)

Pandas (built on NumPy)

Without NumPy → ML would be extremely slow.

8. Advantages in Industrial Scenarios

Fast real-time calculations

Financial modeling

Data analytics pipelines

Scientific simulations

AI systems

Big data preprocessing


   Industries:

Finance

Healthcare

AI companies

Research labs

8. Creating Arrays

1D Array

In [ ]:
a = np.array([1,2,3,4])

2D Array

In [ ]:
b = np.array([[1,2],
              [3,4]])

Zeros & Ones

In [ ]:
np.zeros((2,3))
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

9. NumPy Properties

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])


Property - Meaning

ndim -	Number of dimensions

shape	- Rows & columns

size - Total elements

dtype -	Data type

ndmin -	Minimum dimension while creating

In [ ]:
a.ndim    # 2
a.shape   # (2,3)
a.size    # 6
a.dtype   # int32/int64


dtype('int64')

In [ ]:
np.array([1,2,3], ndmin=2)


array([[1, 2, 3]])

10. Difference Between ndim and ndmin

| ndim                    | ndmin                     |
| ----------------------- | ------------------------- |
| Property                | Parameter                 |
| Shows actual dimensions | Forces minimum dimensions |
| Read-only               | Used during creation      |


11. Indexing & Slicing

1D

In [ ]:
a = np.array([10,20,30,40,50])
a[0]      # 10
a[1:4]    # [20 30 40]

array([20, 30, 40])

2D

In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])

b[0,1]      # 2
b[:,1]      # [2 5]
b[0,:]      # [1 2 3]


array([1, 2, 3])

12. Linear Algebra Importance

Without NumPy:

Matrix multiplication is slow

No optimized BLAS/LAPACK

ML models would be inefficient

With NumPy:

np.dot(A, B)

np.linalg.inv(A)

np.linalg.eig(A)

In ML:

Neural networks → matrix multiplication

Regression → linear algebra

PCA → eigenvalues

Optimization → gradient descent

NumPy makes AI computationally feasible.

13. Statistical & Aggregate Functions

In [ ]:
a = np.array([10,20,30,40])

np.mean(a)
np.median(a)
np.sum(a)
np.min(a)
np.max(a)
np.std(a)
np.var(a)


np.float64(125.0)

Axis example:

In [ ]:
np.sum(b, axis=0)


array([5, 7, 9])

14. What is type() Function?

It returns object type.

In [ ]:
type(a)


numpy.ndarray

15. Type Casting in NumPy

In [ ]:
a = np.array([1,2,3])
a.astype(float)

array([1., 2., 3.])

16. Supported Data Types

int8, int16, int32, int64

float16, float32, float64

bool

complex64, complex128

string

object

17. Memory Management in NumPy

Continuous memory allocation

Homogeneous data

Efficient caching

Views instead of copies (slicing creates views)

In [ ]:
b = a[1:3]

No new memory → faster.

18. Importance of NumPy (Use Cases)

Data preprocessing

ML model building

Financial modeling

Signal processing

Image processing

AI research

Scientific computing

19. What is Random in NumPy?

Used to generate random numbers.

In [ ]:
np.random.rand()

0.09927004660161154

Used in:

ML initialization

Simulations

Sampling

20. Types of Random in NumPy

np.random.rand()        # uniform (0,1)

np.random.randn()       # normal distribution

np.random.randint()     # random integers

np.random.choice()      # random selection

np.random.shuffle()     # shuffle array

np.random.seed()        # reproducibility